import { jsPDF } from "jspdf";

export const useGeneratePDF = () => {
  const generatePDF = (data) => {
    const doc = new jsPDF();

    // Event Title
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(22);
    doc.setTextColor(40, 60, 100);
    doc.text("Event Details", 105, 15, { align: "center" });

    // Event Information
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);

    doc.text(`Event Title:`, 10, 30);
    doc.setFont("Helvetica", "bold");
    doc.text(data.title, 40, 30);

    doc.setFont("Helvetica", "normal");
    doc.text(`Description:`, 10, 40);
    doc.text(data.description, 40, 40);

    doc.text(`Start Date:`, 10, 50);
    doc.text(new Date(data.startDate).toLocaleDateString(), 40, 50);

    doc.text(`End Date:`, 10, 60);
    doc.text(new Date(data.endDate).toLocaleDateString(), 40, 60);

    doc.text(`Location:`, 10, 70);
    doc.text(data.location, 40, 70);

    // Divider Line
    doc.setDrawColor(200, 200, 200);
    doc.line(10, 80, 200, 80);

    // Participants Section Title
    doc.setFontSize(18);
    doc.setFont("Helvetica", "bold");
    doc.setTextColor(40, 60, 100);
    doc.text("Participants", 10, 90);

    // Participants Table Header
    doc.setFontSize(12);
    doc.setFont("Helvetica", "normal");
    doc.setTextColor(0, 0, 0);

    let y = 100;

    doc.setFillColor(230, 230, 250);
    doc.rect(10, y, 190, 8, "F");
    doc.text("No.", 12, y + 6);
    doc.text("Username", 40, y + 6);
    doc.text("Email", 120, y + 6);
    y += 10;

    // Loop through participants (users)
    data.participants.forEach((user, index) => {
      if (index % 2 === 0) {
        doc.setFillColor(245, 245, 245);
        doc.rect(10, y, 190, 8, "F");
      }
      doc.text(`${index + 1}`, 12, y + 5);
      doc.text(user.username, 40, y + 5);
      doc.text(user.email, 120, y + 5);
      y += 10;

      // Check for page overflow, and add a new page if needed
      if (y > 280) {
        doc.addPage();
        y = 10;
      }
    });

    // Footer Text
    doc.setFontSize(10);
    doc.setFont("Helvetica", "italic");
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by Event Management System", 105, 290, {
      align: "center",
    });

    // Save the PDF
    doc.save(`${data.title}_EventDetails.pdf`);
  };

  return { generatePDF };
};
